### ISSUE TITLE
Should we use plural syntax in accessing sheets, rows and columns?

### ISSUE THREAD

**Issue by gorn** [gorn/rspreadsheet#10]
Currently the "verbatim" syntax looks like this:

```
book.worksheets(1).rows(5).cells(2).value
```

shouldn't we use this or singular form 

```
book.worksheet(1).row(5).cell(2).value
```

or allow both?

**Comment by milligramme** [comment]
+1 for singular form because `book.worksheet(1).row(5).cell(2).value` each elements return not multiple values

**Comment by richard-kiefer** [comment]
+1 for singular form, because  I read ```book.worksheet(3)``` etc. as a short version of ```book.giveMeWorksheetNumber(3)```. If you were to support array notation like ```book.worksheets[3]``` I supported the plural form, as the array itself is a collection of sheets and the bracket notation picks one from it. Just my humble opinion.

**Comment by gorn** [comment]
It should be mentioned, that currently the method *without* parameter returns array of all rows, cells etc. if we change to singular form, than this probably be "detached" because `book.worksheets(1).rows` returning all rows on 1st sheet is shomehow ok, while `book.worksheet(1).row` doing the same sounds really strange.

**Comment by gorn** [comment]
@richard-kiefer Yes I want to support the "array notation" as is newly [explained here](https://github.com/gorn/rspreadsheet/blob/master/GUIDE.md). And I am not sure if it is good idea to have "verbatim" syntax in singulat and "array" syntax in plural.

Third approach might be to let them work both - it is somehow nonpuristic, but on the other hand superuserfriendly. In that case I would use singular form for "verbatim" syntax in all examples, but the plural form would silently work as well.

**Comment by gorn** [comment]
I have chosen to go with singulars, but aliasing plurals to the singulars, so the principle of least surprise applies.
