### ISSUE TITLE
Monkey patching...

### ISSUE THREAD

**Issue by zekefast** [gorn/rspreadsheet#14]
I have looked into the code of library and saw that library monkey patched two classes: `LibXML::XML::Node` and `Array`.

In general monkey patching should be considered as code smell and all major libraries, like `rspec`, `shoulda-matchers`, `rom` try to reduce it nowadays or eliminate at all.
I suppose that it would be good to make refactoring library to eliminate them or at least use refinements to localize scope of messing other libraries.

IMHO, modification of other libraries classes by monkey patching them could lead to bugs and very nasty side effects. @gorn what's you POV on that?

**Comment by gorn** [comment]
I agree with you, that this is to avoid. Generally I use monkey patching in initial phases of development, because it nicely allows to get on the track (I like this on ruby). But apparently this project has reached next level, so it is time to refactor this out. I will look at refinements.

**Comment by gorn** [comment]
Closing this issue in release v0.2.14 - please have a look. I use refinements for newer versions of ruby (from 2.1, because the keyword "using" fails in ruby 2.0). I leave monkey patching for older ruby, for now, if you have better idea how to do it, let me know.

**Comment by zekefast** [comment]
@gorn Thanks! I shall take a look at it on the weekend.

**Comment by zekefast** [comment]
@gorn I saw usage of refinements, but do not understand where you fallback to monkey patching for Ruby versions which does not support them. So, I can not make reasonable opinion on it. But you can require different files based on ruby version or use forwarding to forward to the same methods from refinements and from monkey patching. That is as a workaround, but in general best approach would be to rewrite code to avoid need in monkey patching at all even with refinements it is still monkey patching...

**Comment by gorn** [comment]
I put all the "optional" code  in https://github.com/gorn/rspreadsheet/blob/master/lib/helpers/class_extensions.rb ... I guess that it will fade away onece ruby 1.9 gois to oblivion.

I understand your point, but I think, that especially in case of LibXML::XML::Node it is more logical usage of ruby open classes than monkeypatching. The thing is, that on many places in code I work with LibXML::XML::Node objects returned by methods of LibXML::XML::Node class (like parent) and I can not imagine the decorator approach, which would enable to add my own methods, yet seemlesly get out of the way if someone else would like to reuse LibXML::XML::Node objects returned by my code. It would mean to dump decorator object and recreate everytime i pass such a thing like a parameter, which for is much uglier. However if you have any insigt at this I will be glad to hear it.

**Comment by gorn** [comment]
Nice article about decorators
