### ISSUE TITLE
Unable to install under Windows

### ISSUE THREAD

**Issue by kumzme** [gorn/rspreadsheet#16]
This could take a while...  
ERROR:  Error installing rspreadsheet:  
        ERROR: Failed to build gem native extension.                                 

```
C:/Ruby21/bin/ruby.exe extconf.rb --without-zlib                                 
```

checking for socket() in -lsocket... no  
checking for gethostbyname() in -lnsl... no  
checking for atan() in -lm... yes  
checking for inflate() in -lfalse... no  
checking for inflate() in -lzlib... no  
checking for inflate() in -lzlib1... no  
checking for inflate() in -llibz... no  
**\* extconf.rb failed **\*  
Could not create Makefile due to some reason, probably lack of necessary  
libraries and/or headers.  Check the mkmf.log file for more details.  You may  
need configuration options.                                                          

Provided configuration options:  
        --with-opt-dir  
extconf failure: need zlib

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby21/lib/ruby/gems/2.1.0/gems/libxml-ruby-2.8.0 for inspection.
Results logged to C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/libxml-ruby-2.8.0/gem_make.out

_____ Troed with Ruby 1.9 and 2.1\* to latest .. why is this

honestly am very very very very frus*

Been searching so many options so many things

is this only for non-windows ?
With and without zlib both i tried

**Comment by kumzme** [comment]
honestly am very very very very frus*

**Comment by gorn** [comment]
Hi, kumzme :)

I do not know if I can help, but let us try. After all that what is open source about. The gem is not intended to be non-windows, but I do not have any experience with Windows, so I can not tell. I do not have the Windows license, so I can not test it. So if you want we can try to locate the error and correct it.

How you are trying to install it? Is there a bundler in windows, or you use something else? It is not obvious from your text.

It is saying that there will be more in mkmf.log file. Can you post it (preferably using gist and not pasting it here as it gets difficult to read).

Also it, mentions that the result of installation is logged into Results logged to C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/libxml-ruby-2.8.0/gem_make.out . Can you post this file as well?

Exactly what versions were used in your test?

**Comment by gorn** [comment]
@kumzme Did you solve this or not? Shall I mark the isssue solved?

**Comment by gorn** [comment]
@kumzme any progress on this?

**Comment by gorn** [comment]
Closing because there is no evidence, that it is still valid.
