### ISSUE TITLE
Anything I can do to speedup?

### ISSUE THREAD

**Issue by bearpku** [gorn/rspreadsheet#17]
I am trying to read a spreadsheet which contains about 8k rows and 50 columns. What I am doing right now is:

```
sheet.used_rows_range.each do |row_id|
    (1..50).each do |col_id|
        value = sheet.cells(row_id, col_id).value
        # do something with value
    end
end
```

it cost almost 1 hour to finish the reading. Anything I can do to speedup?

**Comment by gorn** [comment]
Honestly I did not start to do aby speed optimization yet, because I am using the gem to work with several hundreds of cells so it is non issue. Could you send/attach sample of what you are trying to parse, so I can test it?

**Comment by gorn** [comment]
It does not need to be a document containing real data, just rewrite them with random values, but I need something to udnerstand what you are trying to do.

**Comment by gorn** [comment]
@bearpku any hope you might send your file?

**Comment by gorn** [comment]
No communication from user so closing
