### ISSUE TITLE
Support for formats, borders

### ISSUE THREAD

**Issue by Tvel** [gorn/rspreadsheet#18]
Hi, is there a way to manually set format and borders of cells?

**Comment by gorn** [comment]
Bold, italic and font size was supported long time ago via

cell.format.bold = true
cell.format.font_size = '15pt'

etc. 

Now I have added support for borders like

cell.format.top.color = '#005500'
or
cell.border_top.color = '#005500'

Please have a look at many examples at https://gist.github.com/gorn/b432e6a69e82628349e6

So yes, it is supported. Let me know if you have any issues.

**Comment by gorn** [comment]
Closed by #8d7026d111d9bce8c87d56c2c67684e0a9471c0b

**Comment by gorn** [comment]
Closed by commit #8d7026d111d9bce8c87d56c2c67684e0a9471c0b
