### ISSUE TITLE
Working with Time

### ISSUE THREAD

**Issue by whitehat101** [gorn/rspreadsheet#21]
I was looking into setting a Time (without a date) value into a sheet. I couldn't find an example of this, so I set a time using a desktop app, and attempted to read it back (to ultimately figure out how to set it), and received an exception.

```
irb(main):005:0> sheet.C7
RuntimeError: Unknown type at [7, 3] from <table:table-cell table:style-name="ce13" office:value-type="time" office:time-value="PT02H00M00S" calcext:value-type="time">
  <text:p>2:00</text:p>
</table:table-cell> / children size=1 / type=time
  from /Users/xx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspreadsheet-0.2.15/lib/rspreadsheet/cell.rb:156:in `guess_cell_type'
  from /Users/xx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspreadsheet-0.2.15/lib/rspreadsheet/cell.rb:55:in `value'
  from /Users/xx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspreadsheet-0.2.15/lib/rspreadsheet/worksheet.rb:104:in `method_missing'
  from (irb):5
  from /Users/xx/.rbenv/versions/2.3.3/bin/irb:11:in `<main>'
```

**Comment by gorn** [comment]
What exactly you are trying to achieve? Can you send me the code (or pseudocode) you are expecting to work, so I have nave a look at it?

**Comment by gorn** [comment]
@whitehat101 What exactly you are trying to achieve? Can you send me the code (or pseudocode) you are expecting to work, so I have nave a look at it?

**Comment by whitehat101** [comment]
```ruby
require 'rspreadsheet'
book = Rspreadsheet.open './time.ods'
sheet = book.worksheets(1)
# cell = sheet.A1 # exception
cell = sheet.cells('A1') # works
# cell.to_s # exception
```

Github issues doesn't support ODS uploads, so this is an ODS with it's extension changed to zip (not an ODS inside a zip)
[time.zip](https://github.com/gorn/rspreadsheet/files/631380/time.zip)

I'm looking to set time values like what's in A1. I don't really need `to_s` to work, but the IRB REPL was calling it automatically. I bet I can work with `cell = sheet.cells('A1')` to set this.

**Comment by gorn** [comment]
@whitehat101 Thanks. I will have a look at it.

**Comment by gorn** [comment]
it is failing the test under ruby 2.2.3 ...

**Comment by gorn** [comment]
@whitehat101 ok, it needed one more thing - to clean up the value when changing the cell from time to another type of contant. It works now. There is another issue though and it is the text part of nodes. You set it up with hardcoded format, but I am sure people will want to influence how time looks like in their spreadsheet. Ideally it would be able to accept all usual Calc formatters as well as the Ruby ones. I will investigate this and if you have any ideas, let me know.

**Comment by whitehat101** [comment]
That's completely reasonable about the text value format. I just followed my sample's format. However, all the other formats in `value=` are also using hardcoded formats in their `text:p` nodes, so it seems like user formatters aren't quite a thing yet. (Unless this is being rewritten later?)

While looking at this I found: http://books.evc-cit.info/oobook/ch05.html#table-value-table

> If it contains a simple date, it is stored in the form yyyy-mm-dd; if there is both a day and a time, it is stored in the form yyyy-mm-ddThh:mm:ss.

> The value is stored in the form PThhHmmMss,ffffS (where ffff is the fractional part of a second).

I started considering:
```ruby
  DateFormats = ['%Y-%m-%dT%H:%M:%S', '%Y-%m-%d']
  TimeFormats = ['PT%HH%MM%SS,%LS', 'PT%HH%MM%SS']
```
And then having a method try each format, rescue and try the next format as needed. Right now, if you have a long format field it'll parse without error, but the extra data will be ignored.

But encoding/decoding long time turns out to need slightly different format strings:
```
# %4N works for formatting, but not parsing
# ArgumentError: invalid strptime format - `PT%HH%MM%SS,%4NS'

# parsing with %L preserves the 4 fractional digits
t=Time.strptime Time.now.strftime('PT%HH%MM%SS,%4NS'), 'PT%HH%MM%SS,%LS'
t.nsec
```

In addition to the quirks with time, the long date format is actually better represented by Ruby's DateTime anyways. So, arrays of format strings aren't quite the solution.

My sheet doesn't make use of these features, but since I looked around might as well make notes.

**Comment by gorn** [comment]
@whitehat101 gorn:
I am completely fine with evolutionary approach to rspreadsheet so the change introduced right now is nearly exactly what I would call the "minimum change" to make it work. 

No the format is not supported for other types either, because I did not need it yet. I think that first time I will need it for currency and/or date. At this point I will implement it on some systematical way.

**Comment by gorn** [comment]
Feature implemented to sufficient extend now

**Comment by gorn** [comment]
@whitehat101 see also #23
