### ISSUE TITLE
Trying to use rspreadsheet cloned in OpenBSD/adJ produces "sh: dpkg-query: not found" when running bundle install

### ISSUE THREAD

**Issue by vtamara** [gorn/rspreadsheet#25]
I cloned rspreadsheet and in another directory I started an example  with this Gemfile:
              
gem 'rspreadsheet', path: '../rspreadsheet'
gem 'libxml-ruby', '2.8.0'

When I run bundle install I obtain
sh: dpkg-query: not found  

My platform is adJ/OpenBSD 6.0.

**Comment by gorn** [comment]
See some notes at the pull request here https://github.com/gorn/rspreadsheet/pull/26

**Comment by gorn** [comment]
@vtamara please can you confirm that this solves your problem?

**Comment by vtamara** [comment]
It doesn't produce any weird output now. Thank you.
Comments in https://github.com/gorn/rspreadsheet/pull/26
