### ISSUE TITLE
Regression: Spreadsheets manipulated by rspreadsheet 0.3 and 0.4.1 cannot be opened with Excel (2013, 2016)

### ISSUE THREAD

**Issue by vtamara** [gorn/rspreadsheet#27]
The spreadsheets generated with rspreadsheet 0.2.14 could be opened with Excel {2013,2016}.

I created a minimal project that shows the problem:
https://github.com/vtamara/prob-excel-rspreadsheet03

The error presented by Excel 2016:
![](https://raw.githubusercontent.com/vtamara/prob-excel-rspreadsheet03/master/excel2016.png)

When trying to open a file [min2.ods](https://github.com/vtamara/prob-excel-rspreadsheet03/blob/master/min2.ods?raw=true), generated with rspreadsheet 0.3 (and 0.4.1), from a file [min.ods](https://github.com/vtamara/prob-excel-rspreadsheet03/blob/master/min.ods?raw=true) that can be opened with Excel.

There is no problem opening min2.ods with LibreOffice, just with Excel. 

I understand it is not a bug in rspreadsheet, but possibly in Excel, however IMHO it will be easier to fix in rspreadsheet than in Excel. 

So your help to restore the functionality of rspreadsheet 0.2.14 of writing ODS files that can be opened with Excel will be very much appreciated.

**Comment by gorn** [comment]
@vtamara  I would like to fix this, one, but it is coing to be difficult, as I do not have Excel. 

First of all I need to find out what is the difference is files that makes Excel fail. The best would be if you can hunt down the commit which cases the behaviour. There is a slight chance that this file  https://github.com/gorn/rspreadsheet/commits/master/lib/rspreadsheet/empty_file_template.ods itself is not openable in Excel in its newest verion. If it is so, than it is quite good because it would bu easier to debug it.

**Comment by reviewher** [comment]
@gorn just as a heads up, your suspicion is correct.  https://github.com/gorn/rspreadsheet/blob/master/lib/rspreadsheet/empty_file_template.ods does not open in Excel, giving an opaque "something went wrong" error.

**Comment by vtamara** [comment]
Right, however there is no regression here since the empy file of version 0.2.14 couldn't be opened either: https://github.com/gorn/rspreadsheet/blob/v0.2.14/lib/rspreadsheet/empty_file_template.ods?raw=true

**Comment by vtamara** [comment]
[Here](https://github.com/vtamara/prob-excel-rspreadsheet03/blob/master/empty-excel.ods?raw=true) I uploaded an empty file saved with Excel 2016.

**Comment by gorn** [comment]
There is a strange thing. You are saying that in 0.2.14 it works correctly BUT that the "empty template" file does NOT open. Really? This is more than suspicious. Can you check if it works with file just freshly created with 0.2.14?

**Comment by gorn** [comment]
Ok, on second thought it is not that suspicious and maybe we are looking at two bugs which are unrelated. The reason why the empty-tamplate won't open may be that it does *not* contain some parts as styles.xml etc, which is intentional. It is created later on by the script itself. If the freshly created file in all versions work, than we so not need to worry about that. Can you confirm that freshly created file opens? (From what you have written it seems that it does)

**Comment by gorn** [comment]
BTW I have read the README from the https://github.com/vtamara/prob-excel-rspreadsheet03 and thank a lot for this! It is a great analysis and if it is correct, that it points out the problem. The bug should be in conpression. But the compression is done by rubyzip ... you may try on think thought. If you replace appropriate line in rspreadsheet.gemspec by

> gem 'rubyzip', '>= 1.0.0'

and `budle update` than the newer version or rubyzip 1.2 should install which may be significant.

**Comment by vtamara** [comment]
Before reading your comments I was understanding more the minimal empty file that Excel can open. By merging https://github.com/gorn/rspreadsheet/blob/v0.2.14/lib/rspreadsheet/empty_file_template.ods?raw=true and the empty file created with Excel that I referenced before , I could create:
- [An empty spreadsheet that can be opened in Excel with warnings](https://github.com/vtamara/prob-excel-rspreadsheet03/blob/master/empty-noerrors-excel.ods?raw=true)
- [An empty spreadsheet that can be opened in Excel without warnings](https://github.com/vtamara/prob-excel-rspreadsheet03/blob/master/empty-nowarnings-excel.ods?raw=true)

What I notice is that an empty file in Excel must have at least one sheet in contents.xml, and to avoid warnings initially it requires styles.xml and meta.xml.

I will try the test you are asking.  Opening a freshly generated file by 0.2.14 with Excel.

**Comment by vtamara** [comment]
Yes a new file generated with 0.2.14 can be opened with Excel (after ignoring a warning).

**Comment by gorn** [comment]
This is good test, but does not help that much. I prefer the "empty template" to be minimalistic and do not contain more information than necessary. "Empty" files from LibreOffice/Excelusually contain lots of things which depend on language of your installation and I do not want to include that etc. The sheet to content.xml is added by script itself, as well as styles and meta changes.

I dug little into the version history and there was massive rewrite of save features around commit cadd2e2d3714a3e6. It could help if you are willing to browse through versions and try to find out when the regression started to be present.

**Comment by vtamara** [comment]
Changing the specfile and running bundle update, didn't help.

After updating rubyzip to 1.2.1 if I unzip the generated file and zip it from the command line it works in Excel.

**Comment by vtamara** [comment]
The problem seems to be in the compression of manifest.xml (not because of newlines but something with the compression that is not supported by Excel).  
To test I made a change in workbook.rb to save  manifest.xml only when it changes (it seems it changes only when there are images).
It is at https://github.com/vtamara/rspreadsheet/commit/acd346da8f2ae13bd56fdfbe70591f89760e5efe

With this change the minimal test I was using is working.

However I guess there  will be problems to open in Excel when the manifest.xml file must be changed.

**Comment by vtamara** [comment]
Since I'm still not using rspreadseet to include new images in any project, for the moment the PR #28  is enough for me, and possibly for other people who was using rspreadsheet before 0.3.   I wish that simple pull request could be accepted or a better solution in the short term could be found , as well as a new version of rspreadsheet including the fix --to start using it the projects where I'm using rspreadsheet (for example https://github.com/pasosdeJesus/sivel2_sjrcol/) instead of sticking to 0.2.14.   

By the way thanks a lot for your hard work with rspreadsheet, very useful gem.  I hope to find time to help fixing more details (including testing the case with images and Excel, and improving speed to generate big spreadsheets).   Blessings.

**Comment by vtamara** [comment]
I squashed the commits of #29 to make it easier to review. I think it solves the regression.

**Comment by gorn** [comment]
Still it would be good to find out when the regression happened and what is the real reason, because this is going to come back when manifest.xml needs to be manipulated.

**Comment by vtamara** [comment]
Right. However for the moment the regression is fixed.  

Could you please release a new version, so people (like me) can use the newest rspreadsheet gem in projects?

**Comment by gorn** [comment]
@vtamara released
