### ISSUE TITLE
Manipulation of a spreadsheet randomly crashes application with "Bus error"

### ISSUE THREAD

**Issue by vtamara** [gorn/rspreadsheet#30]
In OpenBSD/adJ 6.0 with ruby 2.40 and libxml-ruby 2.9.0, running ```bundle exec rspec``` sometimes produces ```Bus error```.  Trace is long, it uses to include:
```
-- Control frame information -----------------------------------------------
c:0027 p:---- s:0152 e:000151 CFUNC  :to_str
c:0026 p:---- s:0149 e:000148 CFUNC  :to_s
c:0025 p:0010 s:0145 e:000144 METHOD /usr/local/lib/ruby/gems/2.4/gems/did_you_mean-1.1.0/lib/did_you_mean/core_ext/name_error.rb:10 [FINISH]
c:0024 p:---- s:0139 e:000138 CFUNC  :inspect
c:0023 p:0046 s:0135 e:000133 METHOD /var/www/bundler/ruby/2.4/gems/rspec-expectations-2.99.2/lib/rspec/matchers/built_in/raise_error.rb:122
```

I see the same kind of errors in the CI at travis, for example:

https://travis-ci.org/gorn/rspreadsheet/jobs/214028477

Running rspec seems to me that produce a bus error every one of three attempts.

**Comment by vtamara** [comment]
I think it is the same error that I reported in #20, that happens with libxml-ruby 2.9.0, an issue in libxml-ruby not resolved (but unfortunately closed) deals with that, see https://github.com/xml4r/libxml-ruby/issues/127

In applications where I use rspreadsheet my workaround in this moment is to use libxml-ruby 2.8.0.

**Comment by gorn** [comment]
I have accepted your pull request and the gem now uses 2.8.0. It seems to be ok now, so I close this bug. Feel free to reopen, if needed.
