### ISSUE TITLE
Setting background color get more cells colorized

### ISSUE THREAD

**Issue by twnaing** [gorn/rspreadsheet#40]
I am trying to set background color using the following code.

```ruby
cell = sheet.cell("#{col}#{row}")
cell.format.background_color = '#EEEEEE'
```

![](https://i.imgur.com/lBS1EX9.png)

_Please see the below screenshot to see the column I want to colorize_

`col` and `row` are generated in nested loop. The following code correctly set the cell with value 'S' (so the col and row calculation is correct)

```ruby
cell.value = 'S'
```

![](https://i.imgur.com/xvuTzwr.png)

I have tried accessing the cells with various methods and rspreadsheet consistently (not random) mis-colorize the background-color of (unintended) cells.

Have anyone experience this problem? Any direction to fix this is much appreciated.

**Comment by gorn** [comment]
Can you provide a failing test? I.e. piece of code, which does not behave the way you would like?

**Comment by twnaing** [comment]
@gorn, thank you for quick response.

Frankly, I do not have test. I am just doing manual testing. 

I updated the issue post with screen shot.

**Comment by gorn** [comment]
I do not need any sofisticated test. I just need to reproduce the error to be able to correct it. 

When I run the following code

```ruby
require 'rspreadsheet'

file = Rspreadsheet.new
sheet = file.create_worksheet

sheet.cell(1,1).value = 'A'
sheet.cell(1,1).format.background_color = '#EEEEEE'

file.save('test.ods')
```

It saves correct document with gray background of cell A1. Can you alter the code so it fails?

**Comment by twnaing** [comment]
@gorn, sorry, I want to apologize for wasting your time.

I found out that the ods file has lot of errors. (I tested it with `jing` according to [this page](https://wiki.oasis-open.org/office/How_to_Validate_an_ODF_document))

ods file converted using the following software/service has the problem discussed in this issue

- converting xlsx file to ods with Microsoft Excel 16.16.8 (190312) on Mac
- converting xlsx file to ods with LibreOffice Version: 6.0.5.2 on Mac
- converting xlsx file to ods with [Zamzar](https://www.zamzar.com/convert/xlsx-to-ods/) and it produces more error than above two methods

At least, I could advise other users not to use ods file converted from other file format.

Thank you for your time and your wonderful gem.

**Comment by gorn** [comment]
You are welcomed, BTW the easiest way to convert is to install LibreOffice. Cals is also superior to Microsoft Spreadsheet tool.

**Comment by twnaing** [comment]
@gorn, I did convert using LibreOffice. Even with LibreOffice, I still experiencing background color bleeding to other unintended cells. I am still testing and couldn't pinpoint the cause.

The worksheet needs to have
- colored background
- merged cells
- conditional formatting
- formulas
- font styles and size set
- image

I will report back here if I found specific feature causing the background-color bleeding.

**Comment by gorn** [comment]
It would be helpful if you are able to isolate reoroducible case. Ie fails everytime. Reooen the issue than.

**Comment by gorn** [comment]
@twnaing even if you do not isolate the problem, it is sufficient for me to have any reproducible failing case. Even complicated one, but it should be reproducible on my side, as a first step to correct it.

**Comment by twnaing** [comment]
@gorn, 

When I changed the background color of the cell (I wanted) the cells (I do not wanted) are also changed __if they have the same format__. It is not specific to feature. 

example 1: if A1 and C10 are bordered in LibreOffice, they will have same background color if I change the background color of A1 by opening the file and saving the file again with rspreadsheet.

Not related to this one, if I 'clear direct formatting' the cell in LibreOffice, rspreadsheet gives error with something like 'no style node'.

I am testing with rspreadsheet 0.4.5, LibreOffice 6.0.5.2 on Mac and the ods file is ODF schema version 1.2

**Comment by gorn** [comment]
That has some logic ... I will try to prepare the file with which it fails

**Comment by gorn** [comment]
Submitted failing test, see also https://travis-ci.org/gorn/rspreadsheet/builds/537741387

**Comment by gorn** [comment]
@twnaing: I have found and corrected the bug. There is a new release ver 0.4.8 for that. Can you upgrade and test it on your side?

**Comment by twnaing** [comment]
@gorn, confirmed. It is working as expected.
