### ISSUE TITLE
Access to document octet string outside of ::Rspreadsheet::Workbook class without file creation.

### ISSUE THREAD

**Issue by zekefast** [gorn/rspreadsheet#7]
# Use case

It is quite common that libraries are used in web frameworks. This is exactly my case and I suppose that many other people are doing the same.

In context of web framework it is not really efficient to create file on server then read it and afterwards delete. What I would like to do is to create document and instead of storing it to the file receive it in binary string which I can then write to file, store in network storage or send it directly to browser with response (and appropriate header).

**Comment by gorn** [comment]
This is generally good and interesting idea. I personally use the gem to manipulate local files, but this is nice usecase as well. Could you elaborate more your usecase? What do you mean by binary string? Can you write a pseudocode which you would expect to work?

**Comment by zekefast** [comment]
@gorn Yeah, sure. I shall post it here when I complete preparation.

**Comment by zekefast** [comment]
@gorn So ... Sorry it takes too long for me to return to this.

Currently the only way to save document is to save it into file on filesystem using [`::Rspreadsheet::Workbook#save`](https://github.com/gorn/rspreadsheet/blob/master/lib/rspreadsheet/workbook.rb#L59) method.

It does not really make sense for web frameworks if you generate reports per request and sent file back as attachment. In that case usage of [`::Rspreadsheet::Workbook#save`](https://github.com/gorn/rspreadsheet/blob/master/lib/rspreadsheet/workbook.rb#L59) method requires from developer to write after that code which would clean up file system from temporary files.

In most cases that situation can be avoided just providing back `IO` instance instead of necessity to write to file.

I think it can be useful to allow to [`::Rspreadsheet::Workbook#save`](https://github.com/gorn/rspreadsheet/blob/master/lib/rspreadsheet/workbook.rb#L59) method returns IO instance in case of absense of file name:

```ruby
workbook.save # => #<StringIO:0x00...>
```

Or it can be a separate interface method for that like `#save_io`.

The trick is to avoid saving data for FS and provide backe `IO` instance.

**Comment by gorn** [comment]
I understand generally the idea, but since I do not use the gem this way (only locally to work with files on disk) it is hard for me to imagine what syntax and usage should be beneficial. Can you post a gist with a code you would like to see running? Why to use StringIO, is not there any better type for binary IOs? (ods file is basically zip file, so it is unreadable stringwise).

**Comment by zekefast** [comment]
@gorn `StringIO` does not make any assumptions about IO's content it just steam of the data. It could be binary or text data. It does not matter. What is matter is that it does not store data to filesystem, you can work with it as with `IO` instance and you can get whole content of the `StringIO` instance with `#string` method.

Unfortunately I do not aware about any other types of `IO`'s. It seems `StringIO` should workout well in this situation.

Ideally I would prefer to inject IO instance in which data should be saved. So, you library does not make any assumption about data storing format and just do what it does best handle spreadsheets.

**Comment by zekefast** [comment]
@gorn I added a dirty [PR](https://github.com/gorn/rspreadsheet/pull/15) to sketch an idea. What do you think?

**Comment by gorn** [comment]
I replied in the pull req., but perhaps it is better to continue here. Regarding the syntax, what about this:

```ruby
spreadsheet = Rspreadsheet.open('filename.ods')
stringio = StringIO.new
spreadsheet.save(stringio)
```
or even this
```ruby
spreadsheet = Rspreadsheet.open('filename.ods')
spreadsheet.save_as_stringio(stringio)
```
or perhaps
```ruby
spreadsheet = Rspreadsheet.open('filename.ods')
stringio = spreadsheet.to_stringio
```
sound good to me ...

**Comment by zekefast** [comment]
@gorn I am completely with anything of this. My refactoring was intended to reuse writing to `IO`. So, storing data to file has been built on top of writing to `IO`. So, user in case of necessity of `IO` object can access it just use same methods as libraries itself uses. That way of doing things allow you not to invent each time a new interface when users need new feature. But as I said I am Okay with any approach as long as it provide access to `IO`.

**Comment by gorn** [comment]
@zekefast i have reused the core of your code to implement save_to_io method. Can you have a look at it. Does it satisfy what you need? I have hard time to write a test for it however, have a look at the bottom of [rspreadsheet_spec.rb](https://github.com/gorn/rspreadsheet/blob/master/spec/rspreadsheet_spec.rb), there is a test which does not work well (I put :skip to it so it is ignorede for now). Do you know how to catch the StringIO stream and save it to binary file?

**Comment by zekefast** [comment]
@gorn Nice! Thank you a lot! I shall check it a bit later today or tomorrow!

**Comment by zekefast** [comment]
@gorn to write file binary you need to open it with a `b` mode (for example, `"wb+"`) or use `File::BINARY` constant. Please, see documentation for [`b`](http://ruby-doc.org/core-2.2.0/IO.html#method-c-new) mode or for [`BINARY`](http://ruby-doc.org/core-2.2.0/File/Constants.html) constant.

Also here is couple of notes on test improvements:
- I would suggest not to use global variables in tests and use `let` instead. You can reuse them with shared examples also.
- Try to consider [`fakefs`](https://rubygems.org/gems/fakefs) to not bothering with file system cleanup during test runs.
- In that particular [test](https://github.com/gorn/rspreadsheet/blob/master/spec/rspreadsheet_spec.rb#L147) you are testing equality of file content would not be more proper way to calculate MD5 checksum for files or compare them as strings before zipping?

**Comment by gorn** [comment]
I admit that I had difficulty to write the test for your issue, since I am not going to use the feature. Could you write one in separate pull request (or corrent mine, which currently does not pass).

**Comment by gorn** [comment]
> In that particular test you are testing equality of file content would not be more proper way to calculate MD5 checksum for files or compare them as strings before zipping?

I think MD5 is not a good idea, because there are lot of things like time stams within the zip file, which will (and have to) be different. That is why I have crafted by "xml_diff" method - this is what we care about - it the files are equivalent xml wise.

**Comment by gorn** [comment]
@zekefast the IO save code was massively refactored. Please give it a try, I wonder if it is suitable to whatever you need to do - the requested feature is implemented, see GUIDE.md. Briefly said, whenever you have IO like object io, you can simply say @workbook.save(io) or @workbook.save_to_io(io).

**Comment by gorn** [comment]
Not only save_to_io works, but the file can now be convertet to_io object, which behaves like normal input stream, curently having read method only (not sure how the write would behave). So one can do something like:

    File.open(@tmp_filename, 'w') do |file| 
      file.write(book.to_io.read) # this does not work
    end

but obviously any other stream can be used, using FIle is quite trivial.
