### ISSUE TITLE
Provide access to document MIME type directly out from document object (::Rspreadsheet::Workbook class).

### ISSUE THREAD

**Issue by zekefast** [gorn/rspreadsheet#8]
# Use case

When you send document content through network it is very to useful to have it. Also it would be good if document object can directly provide you and information about its MIME type and type belongs directly to document.

# Links

- [OpenOffice MIME Types](http://www.openoffice.org/framework/documentation/mimetypes/mimetypes.html)

**Comment by gorn** [comment]
I do not understand exactly what do you mean. The mime type of documents generated is always application/vnd.oasis.opendocument.spreadsheet ... I can easily make it a constant in Rspreadsheet::Workbook class if it solves this issue.

**Comment by zekefast** [comment]
@gorn Yeah. that is what I was thinking about. But probably it rather to make method instead of constant, so it can be accessed through document object.

**Comment by gorn** [comment]
I have implementet it with commit 76bd4e8, so the master gem now does the trick. Can you test it if this is what you want. Optionally I can release new version if you are unable to install from github master.

**Comment by gorn** [comment]
Closing by https://github.com/gorn/rspreadsheet/releases/tag/v0.2.1, please test
